# chunks around that get cleared when /clean is used.
chunk-radius: 2
# items in list will NEVER be cleared by /clean.
# uses Bukkit names: http://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
excluded-items:
  # netherite gear & materials
  - NETHERITE_SWORD
  - NETHERITE_PICKAXE
  - NETHERITE_AXE
  - NETHERITE_SHOVEL
  - NETHERITE_HOE
  - NETHERITE_HELMET
  - NETHERITE_CHESTPLATE
  - NETHERITE_LEGGINGS
  - NETHERITE_BOOTS
  - NETHERITE_INGOT
  - NETHERITE_SCRAP
  - NETHERITE_BLOCK
  - NETHERITE_UPGRADE_SMITHING_TEMPLATE
  # diamond gear & materials
  - DIAMOND_SWORD
  - DIAMOND_PICKAXE
  - DIAMOND_AXE
  - DIAMOND_SHOVEL
  - DIAMOND_HOE
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS
  - DIAMOND
  - DIAMOND_BLOCK
  - DIAMOND_ORE
  - DEEPSLATE_DIAMOND_ORE
  # shulker boxes
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - LIME_SHULKER_BOX
  - PINK_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - RED_SHULKER_BOX
  - BLACK_SHULKER_BOX
  # rare items
  - DRAGON_EGG
  - ELYTRA
  - ENCHANTED_GOLDEN_APPLE
  - ENCHANTED_BOOK
  - TOTEM_OF_UNDYING
  - BEACON
  - HEART_OF_THE_SEA
  - NETHER_STAR
  - END_CRYSTAL
  - TRIDENT
  - DRAGON_BREATH
  - DRAGON_HEAD
  - SPONGE
  - ANCIENT_DEBRIS
  - MUSIC_DISC_13
  - MUSIC_DISC_CAT
  - MUSIC_DISC_BLOCKS
  - MUSIC_DISC_CHIRP
  - MUSIC_DISC_FAR
  - MUSIC_DISC_MALL
  - MUSIC_DISC_MELLOHI
  - MUSIC_DISC_STAL
  - MUSIC_DISC_STRAD
  - MUSIC_DISC_WAIT
  - MUSIC_DISC_OTHERSIDE
  - MUSIC_DISC_5
  - MUSIC_DISC_PIGSTEP
  - MUSIC_DISC_RELIC